name: Auto tag
on:
  push:

jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Tag
        id: create_tag
        uses: jaywcjlove/create-tag-action@v1.1.8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          package-path: ./package.json
